#use_frameworks!

platform :ios, '8.0'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
target 'ZLAlicloudPushManager_Example' do
  pod 'ZLAlicloudPushManager', :path => '../'
  
  target 'ZLAlicloudPushManager_Tests' do
    inherit! :search_paths

    
  end
end
